### ISSUE TITLE
直接用portainer部署

### ISSUE THREAD

**Issue by Yumega** [TakcC/PHP-EPG-Docker-Server#1]
显示 
Forbidden
You don't have permission to access this resource.

**Comment by TakcC** [comment]
应该还是能跑起来吧？这个应该只是warning，因为index.php在epg文件夹底下，导致www文件夹没有index文件。访问ip:5678/epg也提示Forbidden么？

**Comment by TakcC** [comment]
> > 应该还是能跑起来吧？这个应该只是warning，因为index.php在epg文件夹底下，导致www文件夹没有index文件。访问ip:5678/epg也提示Forbidden么？
> 
> 这个能聚合各种epg吗 包括国外的 台湾的

能访问到的 xml 文件就行，格式是统一的。

不过这个现在还做得比较粗糙。对于 DIYP 是有做聚合，对于 xmltv 的话，目前是直接存列表的第一个。

**Comment by TakcC** [comment]
> > > > 应该还是能跑起来吧？这个应该只是warning，因为index.php在epg文件夹底下，导致www文件夹没有index文件。访问ip:5678/epg也提示Forbidden么？
> > > 
> > > 
> > > 这个能聚合各种epg吗 包括国外的 台湾的
> > 
> > 
> > 能访问到的 xml 文件就行，格式是统一的。
> > 不过这个现在还做得比较粗糙。对于 DIYP 是有做聚合，对于 xmltv 的话，目前是直接存列表的第一个。
> 
> 建议做成docker 一键安装， 不用手动拉取 https://github.com/TakcC/PHP-EPG-Docker-Server.git

嗯嗯，已经在着手准备了。今天试了一下，轻量级的alpine-apache-php还有点问题。如果直接用php-apache镜像的话又担心太大了。话说你一般会关注镜像大小么？

**Comment by TakcC** [comment]
> > > > > > 应该还是能跑起来吧？这个应该只是warning，因为index.php在epg文件夹底下，导致www文件夹没有index文件。访问ip:5678/epg也提示Forbidden么？
> > > > > 
> > > > > 
> > > > > 这个能聚合各种epg吗 包括国外的 台湾的
> > > > 
> > > > 
> > > > 能访问到的 xml 文件就行，格式是统一的。
> > > > 不过这个现在还做得比较粗糙。对于 DIYP 是有做聚合，对于 xmltv 的话，目前是直接存列表的第一个。
> > > 
> > > 
> > > 建议做成docker 一键安装， 不用手动拉取 [TakcC/PHP-EPG-Docker-Server.git](https://github.com/TakcC/PHP-EPG-Docker-Server.git)
> > 
> > 
> > 嗯嗯，已经在着手准备了。今天试了一下，轻量级的alpine-apache-php还有点问题。如果直接用php-apache镜像的话又担心太大了。话说你一般会关注镜像大小么？
> 
> 500m 以内都可以😇

哈哈哈，那估计随便哪个都不会超过。在整合alpine-apache-php，那个只有几十M，不过有的地方还没改好。今晚先搞个基于官方php:apache的吧。

**Comment by TakcC** [comment]
> 感谢，已经配置好了，51zmt.top的没问题，但是这种读取不出来 http://m3u4u.com/xml/jq2zy9gxdefwdrejyxr5
> 
> Fatal error: Uncaught Exception: 不支持文件格式xr5 in /var/www/html/epg/update.php:111 Stack trace: #0 /var/www/html/epg/update.php(235): downloadData('http://m3u4u.co...', Object(PDO), Array) #1 {main} thrown in /var/www/html/epg/update.php on line 111

啊……这个版本我只做了基本的URL判断后缀，下个版本把重定向的也加进来吧。

**Comment by TakcC** [comment]
新版本已支持。
