### ISSUE TITLE
过滤“精彩节目”

### ISSUE THREAD

**Issue by snowie2000** [TakcC/PHP-EPG-Docker-Server#12]
使用中发现很多xmltv中将不支持的节目都默认返回了“精彩节目”，并且程序总是使用列表中靠后的epg覆盖靠前的epg，导致如a网站返回了正常的节目，b网站返回精彩节目，则最终输出为……精彩节目。

建议在合并多个xmltv时，将精彩节目项全部过滤掉

**Comment by TakcC** [comment]
是xmltv源头返回精彩节目吗？能否提供地址我测试一下。
现在的逻辑是以靠前的为准，如果同一个频道同一天更新过的话，后面就不会再更新。

**Comment by TakcC** [comment]
不知道你会不会是用了之前版本，之前版本有点小问题，后面会覆盖前面的。最近几个版本改过来了，以前面的为准。

**Comment by snowie2000** [comment]
各个epg都可能是不全的，例如112114的可能没有海外的，livednow又没有国内的，需要相互补充才是最好的。无论是前面优先还是后面优先都会存在变成精彩节目的问题呀

**Comment by TakcC** [comment]
现在就是相互补充啊，没搞懂你的意思。A没的会用B的补全。

**Comment by TakcC** [comment]
你的意思是原本的xml文件就有精彩节目，要过滤掉吗？

**Comment by snowie2000** [comment]
是的我就是这个意思，其实我本来以为没预告就没有呗，结果发现很多xml中含有大量精彩节目或者暂不提供预告之类的无效epg，污染了最终结果

**Comment by TakcC** [comment]
因为每个EPG源的情况不同，不好处理。打算通过频道绑定EPG源来解决。

**Comment by snowie2000** [comment]
绑定频道是可以解决的，但是会大大增加操作负担。
我有个想法不知道是否会拖慢处理速度：虽然每个epg源可能会用不同的文字来占位，有的叫“精彩节目”，有的叫“无预告”，但他们都有一个相同的特点，就是一整天的节目全是一样的。如果判断连续N个节目全是相同文字，或者一天的节目全部都是相同的文字，则忽略此epg源对这个节目的预告。

**Comment by TakcC** [comment]
我之前也想过这个方案，就是全天节目都一样的话，就忽略。不过不知道会不会误杀。先按照这个吧，对效率影响不大的。

**Comment by snowie2000** [comment]
感觉问题不大，正常电视台不太可能出现这个一整天都是一个节目的现象。退一步说如果真有这样的电视台，那这个电视台貌似也不需要节目预告……

**Comment by TakcC** [comment]
嗯嗯，更新了，有空试试。

**Comment by snowie2000** [comment]
更新到最新版试了下，效果确实很不错

**Comment by hecarli555** [comment]
> 各个epg都可能是不全的，例如112114的可能没有海外的，livednow又没有国内的，需要相互补充才是最好的。无论是前面优先还是后面优先都会存在变成精彩节目的问题呀

请教一下，livedown的xml貌似用这个项目拉取不下来吧？我测试了几次拉取livedown都是空的、、、

**Comment by taksssss** [comment]
> > 各个epg都可能是不全的，例如112114的可能没有海外的，livednow又没有国内的，需要相互补充才是最好的。无论是前面优先还是后面优先都会存在变成精彩节目的问题呀
> 
> 请教一下，livedown的xml貌似用这个项目拉取不下来吧？我测试了几次拉取livedown都是空的、、、

提示什么呢？如果是下载失败的话，一般就是网络问题或者跨域限制。
URL给一下。

**Comment by taksssss** [comment]
你说的是livednow么？那个我有做gitee的镜像。那个源很多限制，github action还要用代理才能下载。

**Comment by taksssss** [comment]
https://gitee.com/taksssss/tv

**Comment by hecarli555** [comment]
> https://gitee.com/taksssss/tv

感谢大佬指路66666

**Comment by hecarli555** [comment]
> https://gitee.com/taksssss/tv

很奇怪，我已经加上去并拉取成功了，但是实际上livedown的节目配对不上epg。。。。

**Comment by taksssss** [comment]
数据库里面正常么？
