### ISSUE TITLE
希望使用nginx或者 lighttpd 替换apache

### ISSUE THREAD

**Issue by phoenixxie0** [TakcC/PHP-EPG-Docker-Server#2]
apache镜像过大，希望换成nginx或者 lighttpd 。更适合小容量的盒子或者路由器

**Comment by TakcC** [comment]
> apache镜像过大，希望换成nginx或者 lighttpd 。更适合小容量的盒子或者路由器

已经改成alpine了，上传DockerHub后20M，拉取解压后60M。还有点小调整，这两天会发。

**Comment by phoenixxie0** [comment]
http服务器用apache还是大一些了，换更小的轻量化的会好很多，单进程即可

**Comment by TakcC** [comment]
看了一下 alpine nginx php 的，好像也差不多？DockerHub上面的压缩包基本上都是20~30M。更小的，可能依赖会不全。

**Comment by TakcC** [comment]
你可以试试今天发的新版本，我本身就是在斐讯T1上跑。arm跟x86-64版本都有提供。

**Comment by phoenixxie0** [comment]
NICE了。
