### ISSUE TITLE
XML疑问(・・)?

### ISSUE THREAD

**Issue by YanG-1989** [TakcC/PHP-EPG-Docker-Server#3]
作者打算有聚合xml的打算吗？
自动根据需求分配diy还是xml吗？
若有聚合打算，希望提上进度！
平时只用xml的🤓..这项目适合我这种懒人！谢谢啦...
后期如果能去处重复epg，优化数据会更好！
但是我并不在意项目和数据大小，怕你后期没事情做了🤣...

**Comment by TakcC** [comment]
嗯嗯，后面会做。
我现在是各个格式都生成好，取的时候可以秒取。
坏处就是各个方式都要在存之前就处理好，会有冗余。
DIYP跟超级直播的，我是用频道+日期作为主键，已经存在就不插入。
不知道xml有什么好方法，难道是再从DIYP的json里面重组么？hhh。

**Comment by YanG-1989** [comment]
对epg没啥研究....
不能像diyp 那样直接聚合吗？

目前看到diyp数据就是直接叠加在里面...
也是很多重复的..

如果xml不能直接聚合。
也可以考虑用php或者py对diyp数据转换成xml...

**Comment by TakcC** [comment]
diyp 是按 日期+频道 作为单条数据插入数据库，xml的话是一整条，所以还是有点差别。
我回头参考别人的做法，数据库存原始数据吧。
需要哪种再生成哪种，好像速度也挺快的，而且灵活很多，数据也不会冗余。

**Comment by YanG-1989** [comment]
那样的话xml，说到底还是需要脚本进行整合，就看你想要用哪种方式了。
直接多个xml进行缝合，还是对dipy数据进行转换。
单纯数据本地转换这种脚本处理还是非常快的的...

😎期待下次更新...

**Comment by TakcC** [comment]
嗯嗯，打算从diyp的数据重新转换成xml了。
因为本身diyp的数据就有去重（同一个节目同一个日期，不重复存），不需要额外工作。

**Comment by TakcC** [comment]
支持整合 xmltv 了，返回 .xml.gz 格式文件。有空试试有没bug。:)

**Comment by YanG-1989** [comment]
用了下暂时好像没什么问题...
先体验下！😁
非常好....

**Comment by TakcC** [comment]
嗯嗯 :) 
你的直播源也很给力，之前就在用了！
