### ISSUE TITLE
TiviMate不支持http://{服务器IP地址}:5678/epg/index.php

### ISSUE THREAD

**Issue by ywgf88** [TakcC/PHP-EPG-Docker-Server#4]
我是小白，不是很懂。
按照该部署要求，在docker里部署成功，通过网页可以打开，但是使用TiviMate输入epg网址后，提示地址错误，所以想咨询一下如何在TivaMatr里导入epg服务地址？

**Comment by TakcC** [comment]
你用Docker部署，浏览器能打开的话，TiviMate可以直接填 `http://{服务器IP地址}:5678/epg` 试试。

**Comment by ywgf88** [comment]
重新部署了docker，然后在TiviMate里添加http://{服务器IP地址}:5678/epg/index.php和http://{服务器IP地址}:5678/epg两种规格地址，但是TiviMate更新的电视节目为0，不知道什么原因
![a](https://github.com/user-attachments/assets/39151737-fbfa-4715-bed3-4ce9d31860ff)
![b](https://github.com/user-attachments/assets/66c32103-e328-46a9-8542-7480411d9d17)
![a](https://github.com/user-attachments/assets/e181eeec-dba7-4eb7-ac7c-8a1c0b9438a7)
![b](https://github.com/user-attachments/assets/f3c18401-ace6-4fb1-9327-51921d999ac5)
0

**Comment by TakcC** [comment]
直接浏览器访问 `http://{服务器IP地址}:5678/epg`，能返回xml文件么？

**Comment by ywgf88** [comment]
直接访问是这样的
![Screenshot_2024-07-23-06-39-17-395_com android chrome-edit](https://github.com/user-attachments/assets/d72fee34-0795-4f9e-ae4c-2c3d6ce2ff8d)

**Comment by TakcC** [comment]
你这个看上去又一切正常……你的EPG地址能发一下么？我试试。

**Comment by ywgf88** [comment]
我的epg地址是从你的教程里抠出来的，其实我不知道如何使用，完全是看你的教程做
![Screenshot_2024-07-25-06-39-36-685_com chrome beta-edit](https://github.com/user-attachments/assets/81ac7eae-cf9d-4a19-86ab-2d55ce7983d7)

**Comment by TakcC** [comment]
这么奇怪。我晚点会发一个新版本，你可以试试。

**Comment by TakcC** [comment]
版本更新了，可以试试新版还有没有问题。

**Comment by TakcC** [comment]
新版直接整合生成 .xml.gz 文件了，应该不会出问题。

**Comment by ywgf88** [comment]
好的，我晚上试一下
