### ISSUE TITLE
EPG 拉取失败

### ISSUE THREAD

**Issue by YanG-1989** [TakcC/PHP-EPG-Docker-Server#6]
新版本会出现这问题，是不是对方响应时间太慢了。脚本就直接判断超时失败了？
（老张的epg拉取我会出现这个情况.）

频道忽略和频道映射 不是很懂！
XML 没效果的吧？

体验下来自定义不太好解决...
估计只能根据数据库来自定义囧...

**Comment by TakcC** [comment]
最近老张服务器不知道怎么回事，经常失效，我在用112114跟erw了。

频道忽略跟频道映射，之前版本只在DIYP跟超级直播的请求的时候才处理。

今天的新版本在存数据库的时候也会做处理，所以会影响 xml。

1、先按照频道映射处理，如果能匹配上，原 xml 的频道名就会替换成匹配到的名称；
2、如果匹配不上，会按照频道忽略列表，把原频道名的部分字符删除；
3、频道名统一转换成简体中文进行匹配。

新版本，你把自定义放到频道映射里面就行了。你可以试试，看能不能达到你的需求。

如果是这种的话，那就是

原xml频道名 => 想生成的xml频道名

**Comment by YanG-1989** [comment]
好的.到时候我研究下！
手动gz的压缩包可以下载..
主页确实经常进不去...
