### ISSUE TITLE
Can I get out of Docker?

### ISSUE THREAD

**Issue by mxdabc** [TakcC/PHP-EPG-Docker-Server#8]
Hello👋, my project is https://github.com/mxdabc/epg/

When I saw your project today, I feel that it can be matched with mine, can I get out of the Docker environment and call the native MySQL and Nginx execution? **The SQLite database has been measured, and the data volume will lock the database.**
If so, that's great, **could you please attach your Apache config file?**

I'll operate the rest.

**Comment by TakcC** [comment]
这个版本在php7.x版本上面也测试过了，可以直接部署运行。
我自己在Docker跟1panel面板部署的OpenResty+PHP默认配置上测试过，都能正常运行。
Apache的配置，可以在[docker-entrypoint.sh](https://github.com/TakcC/PHP-EPG-Docker-Server/blob/main/docker-entrypoint.sh)找到。
数据库已经改成PDO连接，SQLite改MySQL稍微改一下就行。
核心代码不多，建议直接改写成Python。
你的项目比较庞大，我回头再看看能不能融合进去。

**Comment by mxdabc** [comment]
好的，回头我看看怎么操作。

于 2024年8月10日 GMT+08:00 上午2:49:51，Tak ***@***.***> 写道：
>这个版本在php7.x版本上面也测试过了，可以直接部署运行。
>我自己在Docker跟1panel面板部署的OpenResty+PHP默认配置上测试过，都能正常运行。
>Apache的配置，可以在[docker-entrypoint.sh](https://github.com/TakcC/PHP-EPG-Docker-Server/blob/main/docker-entrypoint.sh)找到。
>数据库已经改成PDO连接，SQLite改MySQL稍微改一下就行。
>核心代码不多，建议直接改写成Python。
>你的项目比较庞大，我回头再看看能不能融合进去。
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/TakcC/PHP-EPG-Docker-Server/issues/8#issuecomment-2278545379
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
Form mxd's Android Phone.

**Comment by mxdabc** [comment]
已完成修改及合并
